<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>MathModelSimulator.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
        <PackageReference Include="OxyPlot.Avalonia" Version="2.1.0-Avalonia11" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Views\MainWindowResources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>MainWindowsResources.Designer.cs</LastGenOutput>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <DependentUpon>MainWindow.axaml</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\MainWindowResources.ru.resx">
        <DependentUpon>MainWindowResources.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\MainWindowResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>MainWindowResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Pages\HomePageView.axaml.cs">
        <DesignTime>True</DesignTime>
        <DependentUpon>HomePageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ModelPageView.axaml.cs">
        <DesignTime>True</DesignTime>
        <DependentUpon>ModelPageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AboutDialogView.axaml.cs">
        <SubType>Code</SubType>
        <DependentUpon>AboutDialogView.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MathModelSimulator.Domain\MathModelSimulator.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\AboutDialog.axaml" />
    </ItemGroup>
</Project>
